services:
  - type: web
    name: link-shortener-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://rakeshsagar89.github.io/ProjectLink/
      - key: SPRING_PROFILES_ACTIVE
        value: prod
